export const mockPortfolios = [
  {
    id: "1",
    title: "Brand Identity Design for Sustainable Fashion Startup",
    author: {
      name: "Sarah Chen",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
      role: "Brand Designer",
    },
    thumbnail: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=600&fit=crop",
    category: "Branding",
    reviewCount: 24,
    viewCount: 1420,
    rating: 4.8,
    featured: true,
    description: "Complete brand identity system including logo design, color palette, typography, and brand guidelines for an eco-conscious fashion brand targeting millennials.",
    files: [
      { type: "image", url: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1200&h=800&fit=crop", name: "Brand Overview" },
      { type: "image", url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=800&fit=crop", name: "Logo Variations" },
      { type: "image", url: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=1200&h=800&fit=crop", name: "Color System" },
    ],
  },
  {
    id: "2",
    title: "Mobile Banking App UI/UX Redesign",
    author: {
      name: "Marcus Johnson",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
      role: "Product Designer",
    },
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
    category: "UI/UX",
    reviewCount: 18,
    viewCount: 892,
    rating: 4.5,
    featured: false,
    description: "A complete redesign of a mobile banking application focusing on improved user experience, accessibility, and modern visual design patterns.",
    files: [
      { type: "image", url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&h=800&fit=crop", name: "App Overview" },
      { type: "image", url: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1200&h=800&fit=crop", name: "Dashboard Design" },
    ],
  },
  {
    id: "3",
    title: "Architectural Visualization Portfolio",
    author: {
      name: "Elena Rodriguez",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
      role: "3D Artist",
    },
    thumbnail: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800&h=600&fit=crop",
    category: "3D Design",
    reviewCount: 31,
    viewCount: 2105,
    rating: 4.9,
    featured: true,
    description: "High-quality architectural visualizations showcasing residential and commercial projects with photorealistic rendering techniques.",
    files: [
      { type: "image", url: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=1200&h=800&fit=crop", name: "Modern Villa" },
      { type: "image", url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop", name: "Urban Complex" },
    ],
  },
  {
    id: "4",
    title: "Editorial Illustration Series",
    author: {
      name: "Tom Williams",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
      role: "Illustrator",
    },
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=600&fit=crop",
    category: "Illustration",
    reviewCount: 12,
    viewCount: 654,
    rating: 4.3,
    featured: false,
    description: "A collection of editorial illustrations created for various publications, exploring themes of technology, society, and human connection.",
    files: [
      { type: "image", url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&h=800&fit=crop", name: "Tech Future" },
    ],
  },
  {
    id: "5",
    title: "E-commerce Website Design System",
    author: {
      name: "Aisha Patel",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop",
      role: "Design Lead",
    },
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop",
    category: "Web Design",
    reviewCount: 42,
    viewCount: 3201,
    rating: 4.7,
    featured: true,
    description: "Comprehensive design system for a luxury e-commerce platform including components, patterns, and design tokens.",
    files: [
      { type: "image", url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop", name: "Design System" },
      { type: "image", url: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?w=1200&h=800&fit=crop", name: "Component Library" },
    ],
  },
  {
    id: "6",
    title: "Motion Graphics Showreel 2024",
    author: {
      name: "James Kim",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
      role: "Motion Designer",
    },
    thumbnail: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&h=600&fit=crop",
    category: "Motion",
    reviewCount: 8,
    viewCount: 421,
    rating: 4.6,
    featured: false,
    description: "Collection of motion graphics work including brand animations, explainer videos, and social media content.",
    files: [
      { type: "video", url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&h=800&fit=crop", name: "Showreel" },
    ],
  },
];

export const mockComments = [
  {
    id: "c1",
    author: {
      name: "David Park",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop",
      role: "Creative Director at Studio Nova",
      isExpert: true,
    },
    content: "Excellent work on the brand identity! The color palette really captures the sustainable, eco-friendly essence of the brand. I particularly love how you've balanced modern aesthetics with organic elements. One suggestion: consider adding more contrast in the secondary color variations for better accessibility.",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    likes: 12,
    replies: [
      {
        id: "c1r1",
        author: {
          name: "Sarah Chen",
          avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
          role: "Brand Designer",
        },
        content: "Thank you so much for the thoughtful feedback, David! You make a great point about the contrast. I'll work on some variations with higher contrast ratios for the secondary palette.",
        createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
        likes: 5,
      },
      {
        id: "c1r2",
        author: {
          name: "Lisa Thompson",
          avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
          role: "Senior Designer",
        },
        content: "I agree with David's point! Also wanted to add that the logo mark is very versatile. Have you tested it at smaller scales for favicon or app icon usage?",
        createdAt: new Date(Date.now() - 45 * 60 * 1000),
        likes: 3,
      },
    ],
  },
  {
    id: "c2",
    author: {
      name: "Michael Torres",
      avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&h=100&fit=crop",
      role: "Brand Strategist",
      isExpert: true,
    },
    content: "The typography choices are spot-on for the target demographic. The combination of the geometric sans-serif with the hand-drawn elements creates a nice tension between professional and approachable. Would love to see how this translates to digital advertising formats.",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    likes: 8,
    replies: [],
  },
  {
    id: "c3",
    author: {
      name: "Emma Wilson",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop",
      role: "UX Designer",
    },
    content: "Beautiful work! The brand guidelines document is incredibly well-organized. Quick question: did you consider creating a dark mode version of the brand assets? That might be useful for the digital applications.",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    likes: 6,
    replies: [
      {
        id: "c3r1",
        author: {
          name: "Sarah Chen",
          avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
          role: "Brand Designer",
        },
        content: "Great suggestion, Emma! I actually have dark mode variants in the works. I'll update the portfolio with those soon.",
        createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000),
        likes: 2,
      },
    ],
  },
];

export const categories = [
  "All",
  "Branding",
  "UI/UX",
  "Web Design",
  "Illustration",
  "3D Design",
  "Motion",
  "Photography",
  "Print",
];
